// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzdEAz2HyC8pCxZiQHT9-5lERL9owMQSM',
    appId: '1:266765369698:web:b4d7c3d7e302a7dd8bec3b',
    messagingSenderId: '266765369698',
    projectId: 'eos-chatting-7c5f4',
    authDomain: 'eos-chatting-7c5f4.firebaseapp.com',
    storageBucket: 'eos-chatting-7c5f4.appspot.com',
    measurementId: 'G-0XWQQ510G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzVBJBJ5UJZ6xjQNs8pyE30ANljCcuzE',
    appId: '1:266765369698:android:a94db0d4e961868d8bec3b',
    messagingSenderId: '266765369698',
    projectId: 'eos-chatting-7c5f4',
    storageBucket: 'eos-chatting-7c5f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdW6t9d2BSXlGdxAhGPgjFCuzz9VDojcw',
    appId: '1:266765369698:ios:557d9d8f9131e8b68bec3b',
    messagingSenderId: '266765369698',
    projectId: 'eos-chatting-7c5f4',
    storageBucket: 'eos-chatting-7c5f4.appspot.com',
    iosClientId: '266765369698-am3slsnmp69k2rj7hkg9d92729pbqckg.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );
}
